{
  "contest": 116,
  "handle": "0xDjango",
  "address": "0x5938Dc681121c306192F3187a3EEe47B9C697BA0",
  "risk": "3",
  "title": "Batch Transfer will likely fail on ERC777 transfers, either maliciously or accidentally",
  "issueId": 83,
  "issueUrl": "https://github.com/code-423n4/2022-05-cudos-findings/issues/83"
}